name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:

    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page-url }}

    steps:

      - uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get install pandoc

      - name: Build with pdblog
        run: ./pdblog.sh

      - name: Package the site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
